Tensors

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-2.0631e+15,  4.5883e-41, -2.0631e+15],
        [ 4.5883e-41, -2.6633e+15,  4.5883e-41],
        [ 1.5302e-38,  0.0000e+00,  1.5301e-38],
        [ 0.0000e+00, -2.9908e+15,  4.5883e-41],
        [-2.8880e+15,  4.5883e-41,  6.2538e+34]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3971, 0.5770, 0.9420],
        [0.0466, 0.0895, 0.9222],
        [0.4556, 0.0983, 0.1222],
        [0.0529, 0.2314, 0.2644],
        [0.4263, 0.1648, 0.1499]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)  
print(x) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.7779,  0.2658,  0.0142],
        [ 1.3241,  2.1403,  0.6396],
        [-0.6957, -0.4768, -1.1470],
        [ 0.7365, -1.3257, -1.0707],
        [-1.8053, -1.7717, -1.3325]])


In [9]:
print(x.size())

torch.Size([5, 3])


Operations

In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.1761,  0.5273,  0.2440],
        [ 2.1572,  3.1285,  0.7198],
        [-0.4433,  0.5024, -1.0773],
        [ 1.0486, -0.3948, -0.8221],
        [-1.3919, -1.1484, -0.4270]])


In [11]:
print(torch.add(x, y))

tensor([[-0.1761,  0.5273,  0.2440],
        [ 2.1572,  3.1285,  0.7198],
        [-0.4433,  0.5024, -1.0773],
        [ 1.0486, -0.3948, -0.8221],
        [-1.3919, -1.1484, -0.4270]])


In [12]:
y.add_(x)
print(y)

tensor([[-0.1761,  0.5273,  0.2440],
        [ 2.1572,  3.1285,  0.7198],
        [-0.4433,  0.5024, -1.0773],
        [ 1.0486, -0.3948, -0.8221],
        [-1.3919, -1.1484, -0.4270]])


In [13]:
print(x[:,1])

tensor([ 0.2658,  2.1403, -0.4768, -1.3257, -1.7717])


In [14]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2786])
-0.27855196595191956


Numpy Bridge

In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [20]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))